name: Go Release

on:
  release:
    types: [published]

jobs:

  release:
    if: github.repository == 'PasteUs/HelloCI'
    name: Build with go ${{ matrix.go_version }} on ${{ matrix.os }} and upload
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go_version: [1.13]
        os: [ubuntu-latest]

    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1


      - name: Gzip
        run: |
          mkdir hello-word-${{ matrix.os }}
          cp main hello-word-${{ matrix.os }}
          tar -czvf hello-word-${{ matrix.os }}.tar.gz hello-word-${{ matrix.os }}

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: hello-word-${{ matrix.os }}.tar.gz application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOKEN }}